version: '3'
services:
  tridoc:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - "fuseki"
    volumes:
      - ./blobs:/usr/src/app/blobs
    environment:
      TRIDOC_PWD: "${TRIDOC_PWD}"
  fuseki:
    image: "linkedsolutions/fuseki"
    environment:
      ADMIN_PASSWORD: "pw123"
    volumes:
      - ./fuseki-base:/fuseki/base
      - ./config-tdb.ttl:/fuseki/set-up-resources/config-tdb